// THIS FILE IS AUTO-GENERATED BY scripts/generate-news.mjs
// Do not edit manually. Run "node scripts/generate-news.mjs" to regenerate.

import md_1_en from '../pages/articles/markdown-news/1.en.md'
import md_1_es from '../pages/articles/markdown-news/1.es.md'
import md_1_it from '../pages/articles/markdown-news/1.it.md'
import md_1_zh from '../pages/articles/markdown-news/1.zh.md'
import md_2_en from '../pages/articles/markdown-news/2.en.md'
import md_2_es from '../pages/articles/markdown-news/2.es.md'
import md_2_it from '../pages/articles/markdown-news/2.it.md'
import md_2_zh from '../pages/articles/markdown-news/2.zh.md'
import md_3_en from '../pages/articles/markdown-news/3.en.md'
import md_3_es from '../pages/articles/markdown-news/3.es.md'
import md_3_it from '../pages/articles/markdown-news/3.it.md'
import md_3_zh from '../pages/articles/markdown-news/3.zh.md'
import md_4_en from '../pages/articles/markdown-news/4.en.md'
import md_4_es from '../pages/articles/markdown-news/4.es.md'
import md_4_it from '../pages/articles/markdown-news/4.it.md'
import md_4_zh from '../pages/articles/markdown-news/4.zh.md'
import md_5_en from '../pages/articles/markdown-news/5.en.md'
import md_5_es from '../pages/articles/markdown-news/5.es.md'
import md_5_it from '../pages/articles/markdown-news/5.it.md'
import md_5_zh from '../pages/articles/markdown-news/5.zh.md'

const contentMap: Record<string, Record<string, string>> = {
  "1": {
  "en": md_1_en,
  "es": md_1_es,
  "it": md_1_it,
  "zh": md_1_zh
  },
  "2": {
  "en": md_2_en,
  "es": md_2_es,
  "it": md_2_it,
  "zh": md_2_zh
  },
  "3": {
  "en": md_3_en,
  "es": md_3_es,
  "it": md_3_it,
  "zh": md_3_zh
  },
  "4": {
  "en": md_4_en,
  "es": md_4_es,
  "it": md_4_it,
  "zh": md_4_zh
  },
  "5": {
  "en": md_5_en,
  "es": md_5_es,
  "it": md_5_it,
  "zh": md_5_zh
  }
}

export function getArticleContent(id: string | undefined, lang: string) {
  if (!id) return ''
  const article = contentMap[id]
  if (!article) return ''
  return article[lang] || article['en'] || ''
}
