import fs from 'fs/promises'
import path from 'path'

const mdDir = path.join(process.cwd(), 'src', 'pages', 'articles', 'markdown-news')
const outFile = path.join(process.cwd(), 'src', 'lib', 'newsContent.ts')

async function run() {
  try {
    const files = await fs.readdir(mdDir)
    const mdFiles = files.filter(f => f.endsWith('.md'))

    const imports = []
    const map = {} // id -> { lang: varName }

    for (const f of mdFiles) {
      const match = f.match(/^(.+)\.([a-z]{2})\.md$/i)
      if (!match) continue
      const [, id, lang] = match
      const safeId = id.replace(/[^a-z0-9_]/gi, '_')
      const varName = `md_${safeId}_${lang}`
      imports.push({ varName, file: `../pages/articles/markdown-news/${f}` })
      if (!map[id]) map[id] = {}
      map[id][lang] = varName
    }

    // Build file content
    const header = `// THIS FILE IS AUTO-GENERATED BY scripts/generate-news.mjs
// Do not edit manually. Run "node scripts/generate-news.mjs" to regenerate.
\n`

    const importLines = imports.map(i => `import ${i.varName} from '${i.file}'`).join('\n')

    const mapLines = Object.keys(map)
      .sort()
      .map(id => {
        const langs = Object.entries(map[id])
          .map(([lang, varName]) => `  ${JSON.stringify(lang)}: ${varName}`)
          .join(',\n')
        return `  ${JSON.stringify(id)}: {\n${langs}\n  }`
      })
      .join(',\n')

    const fileContent = `${header}${importLines}\n\nconst contentMap: Record<string, Record<string, string>> = {\n${mapLines}\n}\n\nexport function getArticleContent(id: string | undefined, lang: string) {\n  if (!id) return ''\n  const article = contentMap[id]\n  if (!article) return ''\n  return article[lang] || article['en'] || ''\n}\n` 

    await fs.writeFile(outFile, fileContent, 'utf8')
    console.log('Generated', outFile)
  } catch (err) {
    console.error('Failed to generate newsContent:', err)
    process.exit(1)
  }
}

run()
